from autocorrect import Speller
spell = Speller(lang='en')
print(spell('pyton'))
print(spell('aganst'))
print(spell('aerospce'))
print(spell('enginoring'))
print(spell('cammon databose'))
print(spell('guaidance of mossile'))
print(spell('horo'))
print(spell('horo josph'))
print(spell('nvigotion'))
print(spell('guaidance'))
print(spell('mombai'))
print(spell('joice'))
print(spell('sorce'))
print(spell('flog'))
print(spell('mossage'))